### ISSUE TITLE
Suggestion: Cooldown in invitations

### ISSUE THREAD

**Issue by msmanui** [WiIIiam278/HuskTowns#433] opened 2024-03-06 07:55 UTC
Currently, you can spam `/town invite Test` without limit. It would be nice to add "You already invited player, please wait..." 
The other player will recive all the invitations as well, so it's very annoying.

**Comment by WiIIiam278** [comment] 2024-03-06 13:17
Duplicate of https://github.com/WiIIiam278/HuskTowns/issues/79

**Closed by WiIIiam278** 2024-03-06 13:17 UTC
