### ISSUE TITLE
[Suggestion] Plot Taxes

### ISSUE THREAD

**Issue by bradleybrand** [WiIIiam278/HuskTowns#428] opened 2024-02-25 10:28 UTC
It would be great to have a taxation system for the town where town residents pay taxes based on the plots that they personally own.

A toggle could enable/disable such feature for those who may or may not want to use the tax system.

Servers have different methods how players earn money, such as Jobs or mob killing rewards.

**Comment by WiIIiam278** [comment] 2024-02-25 10:44
Duplicate of #18

**Closed** 2024-02-25 10:44 UTC
