### ISSUE TITLE
players can remove items from frames on farm chunks

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#459] opened 2024-05-01 01:35 UTC
This happens even if public build access is disabled for farm chunks.

**Comment by WiIIiam278** [comment] 2024-05-04 18:24
so this is because Item Frames are an entity and farm chunks have `OperationType.PLAYER_DAMAGE_ENTITY` set in flags.yml

**Comment by WiIIiam278** [comment] 2024-12-22 16:15
Marking this as works as intended, feel free to modify the flags in farm chunks to disable this.

**Closed by WiIIiam278** 2024-12-22 16:15 UTC
Labels: type: bug, status: needs testing
