### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#437] opened 2024-03-15 01:10 UTC
Hello, I would like to know if it's possible to improve the performance of the plugin, as I'm experiencing significant increases in MSPT. It's not urgent, since despite everything, my server remains stable at 20-19 TPS, but I believe there is room for improvement, especially if we think about scalability. I'm using latest build 3.0.2

https://spark.lucko.me/6cCNCHKC7y

**Comment by ProdPreva1l** [comment] 2024-03-15 01:14
Not sure if there is any way to make it any faster, (atleast for this specific case) just at a quick glance

whats causing it is this function here
```java
    public Optional<TownClaim> getClaimAt(@NotNull Chunk chunk, @NotNull HuskTowns plugin) {
        return claims.entrySet().stream()
                .filter(entry -> entry.getValue().stream().anyMatch(claim -> claim.getChunk().equals(chunk)))
                .findFirst()
                .flatMap(entry -> entry.getValue().stream()
                        .filter(claim -> claim.getChunk().equals(chunk))
                        .findFirst()
                        .flatMap(claim -> plugin.findTown(entry.getKey())
                                .map(town1 -> new TownClaim(town1, claim))))
                .or(() -> adminClaims.stream()
                        .filter(claim -> claim.getChunk().equals(chunk))
                        .findFirst()
                        .map(claim -> new TownClaim(plugin.getAdminTown(), claim)));
    }
    ```
    
    and stream filtering is always going to be slow but, there might be a better way of doing it, someone smarter than me will know more than me though

**Comment by matipoirierg** [comment] 2024-03-15 01:20
> Not sure if there is any way to make it any faster, (atleast for this specific case) just at a quick glance
> 
> whats causing it is this function here
> 
> ```java
>   public Optional<TownClaim> getClaimAt(@NotNull Chunk chunk, @NotNull HuskTowns plugin) {
>        return claims.entrySet().stream()
>                .filter(entry -> entry.getValue().stream().anyMatch(claim -> claim.getChunk().equals(chunk)))
>                .findFirst()
>                .flatMap(entry -> entry.getValue().stream()
>                        .filter(claim -> claim.getChunk().equals(chunk))
>                        .findFirst()
>                        .flatMap(claim -> plugin.findTown(entry.getKey())
>                                .map(town1 -> new TownClaim(town1, claim))))
>                .or(() -> adminClaims.stream()
>                        .filter(claim -> claim.getChunk().equals(chunk))
>                        .findFirst()
>                        .map(claim -> new TownClaim(plugin.getAdminTown(), claim)));
>    }
> ```
> 
> and stream filtering is always going to be slow but, there might be a better way of doing it, someone smarter than me will know more than me though

Catch another spike that actually dropped my tps to 17, but I think it's a different function this time https://spark.lucko.me/ls3a0fXsj9

**Comment by ProdPreva1l** [comment] 2024-03-15 01:22
Different listener but same function, its getting the claim object (if it exists) and checking the flag for that event, it might be better to cache all claims at startup but that could cause higher ram, again not too sure the best way to go about this

**Comment by matipoirierg** [comment] 2024-03-15 01:27
> Different listener but same function, its getting the claim object (if it exists) and checking the flag for that event, it might be better to cache all claims at startup but that could cause higher ram, again not too sure the best way to go about this

thanks for the clarification

**Comment by MSCMDD** [comment] 2024-03-16 12:36
Here is also a performance issue
#425 
![image](https://github.com/WiIIiam278/HuskTowns/assets/128666602/12135fdc-5980-4edb-9fa7-cc1c31d606d1)

**Comment by matipoirierg** [comment] 2024-03-16 19:31
This situation is worse than I anticipated. My TPS is dropping to 14-15, especially when there are high player counts.

**Comment by WiIIiam278** [comment] 2024-03-16 20:22
Seems like we need to take a look at some stream logic & make some optimisations :)

**Comment by WiIIiam278** [comment] 2024-03-17 15:06
Going to close this as a duplicate of #425 :)

**Closed by WiIIiam278** 2024-03-17 15:06 UTC
